server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb
      auto-index-creation: false
  jackson:
    default-property-inclusion: NON_NULL

service:
  client:
    uri: http://localhost:8081/api/client
  account:
    uri: http://localhost:8085/api/v1/account
